export const countriesData = [
    { code: 'DE', name: 'Germany', phonePrefix: '+49', cities: ['Berlin', 'Munich', 'Hamburg', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Leipzig', 'Dortmund', 'Essen'] },
    { code: 'FR', name: 'France', phonePrefix: '+33', cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'] },
    { code: 'IT', name: 'Italy', phonePrefix: '+39', cities: ['Rome', 'Milan', 'Venice', 'Florence', 'Naples', 'Turin', 'Palermo', 'Bologna', 'Genoa', 'Bari'] },
    { code: 'ES', name: 'Spain', phonePrefix: '+34', cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Palma de Mallorca', 'Las Palmas', 'Bilbao'] },
    { code: 'UK', name: 'United Kingdom', phonePrefix: '+44', cities: ['London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Bristol', 'Leeds', 'Sheffield', 'Edinburgh', 'Cardiff'] },
    { code: 'PT', name: 'Portugal', phonePrefix: '+351', cities: ['Lisbon', 'Porto', 'Braga', 'Coimbra', 'Amadora', 'Sintra', 'Almada', 'Loures', 'Oeiras', 'Funchal'] },
    { code: 'NL', name: 'Netherlands', phonePrefix: '+31', cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Groningen', 'Tilburg', 'Almere', 'Breda', 'Nijmegen'] },
    { code: 'BE', name: 'Belgium', phonePrefix: '+32', cities: ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège', 'Bruges', 'Namur', 'Leuven', 'Mons', 'Aalst'] },
    { code: 'SE', name: 'Sweden', phonePrefix: '+46', cities: ['Stockholm', 'Gothenburg', 'Malmo', 'Uppsala', 'Vasteras', 'Orebro', 'Linkoping', 'Helsingborg', 'Norrkoping', 'Lund'] },
    { code: 'NO', name: 'Norway', phonePrefix: '+47', cities: ['Oslo', 'Bergen', 'Stavanger', 'Trondheim', 'Drammen', 'Fredrikstad', 'Porsgrunn', 'Sandefjord', 'Skien', 'Tonsberg'] },
    { code: 'FI', name: 'Finland', phonePrefix: '+358', cities: ['Helsinki', 'Espoo', 'Tampere', 'Oulu', 'Vantaa', 'Turku', 'Jyväskylä', 'Lahti', 'Kuopio', 'Pori'] },
    { code: 'DK', name: 'Denmark', phonePrefix: '+45', cities: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg', 'Randers', 'Kolding', 'Herning', 'Horsens', 'Vejle'] },
    { code: 'CN', name: 'China', phonePrefix: '+86', cities: ['Beijing', 'Shanghai', 'Shenzhen', 'Guangzhou', 'Hangzhou', 'Chengdu', 'Xi\'an', 'Wuhan', 'Chongqing', 'Tianjin'] },
    { code: 'US', name: 'United States', phonePrefix: '+1', cities: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'] },
    { code: 'IR', name: 'Iran', phonePrefix: '+98', cities: ['Tehran', 'Isfahan', 'Shiraz', 'Tabriz', 'Mashhad', 'Ahvaz', 'Kermanshah', 'Qom', 'Karaj', 'Yazd'] },
    { code: 'AE', name: 'United Arab Emirates', phonePrefix: '+971', cities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain', 'Khalifa City', 'Al Ruwais'] },
    { code: 'SA', name: 'Saudi Arabia', phonePrefix: '+966', cities: ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Khobar', 'Dammam', 'Taif', 'Abha', 'Buraidah', 'Tabuk'] },
    { code: 'KW', name: 'Kuwait', phonePrefix: '+965', cities: ['Kuwait City', 'Hawally', 'Salmiya', 'Farwaniya', 'Mubarak Al Kabeer', 'Jahra', 'Ahmadi', 'Al Asimah', 'Khaitan', 'Sabah Al Salem'] },
    { code: 'QA', name: 'Qatar', phonePrefix: '+974', cities: ['Doha', 'Al Rayyan', 'Al Khor', 'Al Wakrah', 'Umm Salal', 'Lusail', 'Madinat ash Shamal', 'Al Daayen', 'Al Shahaniya', 'Al Zubara'] },
    { code: 'OM', name: 'Oman', phonePrefix: '+968', cities: ['Muscat', 'Sohar', 'Salalah', 'Nizwa', 'Bahla', 'Ibra', 'Sur', 'Khasab', 'Rustaq', 'Dhofar'] },
    { code: 'BH', name: 'Bahrain', phonePrefix: '+973', cities: ['Manama', 'Riffa', 'Muharraq', 'A\'ali', 'Isa Town', 'Sitra', 'Hamad Town', 'Zallaq', 'Juffair', 'Malkiya'] },
    { code: 'YE', name: 'Yemen', phonePrefix: '+967', cities: ['Sana\'a', 'Aden', 'Taiz', 'Hodeidah', 'Al Hudaydah', 'Mukalla', 'Zinjibar', 'Ibb', 'Abyan', 'Marib'] },
    { code: 'EG', name: 'Egypt', phonePrefix: '+20', cities: ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said', 'Suez', 'Luxor', 'Aswan', 'Mansoura', 'Tanta'] },
    { code: 'JO', name: 'Jordan', phonePrefix: '+962', cities: ['Amman', 'Zarqa', 'Irbid', 'Aqaba', 'Mafraq', 'Ma’an', 'Salt', 'Tafilah', 'Ajloun', 'Karak'] },
    { code: 'LB', name: 'Lebanon', phonePrefix: '+961', cities: ['Beirut', 'Tripoli', 'Sidon', 'Zahle', 'Tyre', 'Jounieh', 'Baabda', 'Baalbek', 'Batroun', 'Koura'] },
    { code: 'SY', name: 'Syria', phonePrefix: '+963', cities: ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Tartus', 'Hama', 'Deir ez-Zor', 'Idlib', 'Daraa', 'Raqqa'] },
    { code: 'PS', name: 'Palestine', phonePrefix: '+970', cities: ['Gaza', 'Hebron', 'Nablus', 'Ramallah', 'Jenin', 'Bethlehem', 'Tulkarm', 'Qalqilya', 'Salfit', 'Khan Yunis'] }
];
